server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carl0s8466/todo.git
          searchPaths: config-data
          default-label: main
  security:
    user:

      name: elvis
      password: 123456
